// Generated by CoffeeScript 2.5.1
export {
  encode as utf8Encode,
  decode as utf8Decode
} from 'https://deno.land/x/utf8/mod.js';

export {
  default as Xml
} from 'https://deno.land/x/extract/lib/xml.js';

export {
  default as sleep
} from 'https://deno.land/x/rmw_sleep/lib/sleep.js';

//# sourceMappingURL=deps.js.map
